### ISSUE TITLE
Image builder packer name

### ISSUE THREAD

**Issue by outscale-vbr** [outscale-dev/cluster-api-provider-outscale#156]
### What happened

With new version of packer, packer name change from osc to outscale.
And image-builder is based on it to launch ansible specific provider role and playbook.
So new image don't contains our patch cloudinit binaries.

### Step to reproduce

image failed with tag. 

### Expected to happen

No failure.

### Add anything

None

### cluster-api output

None

### Environment

```markdown
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):
- Kernel (e.g. `uname -a`):
- cluster-api-provider-outscale version:
- cluster-api version: 
- Install tools:
- Kubernetes Distribution:
- Kubernetes Diestribution version:
```

**Comment by outscale-hmi** [comment]
Done 
https://github.com/kubernetes-sigs/image-builder/pull/1029
