### ISSUE TITLE
Image builder global permission

### ISSUE THREAD

**Issue by outscale-vbr** [outscale-dev/cluster-api-provider-outscale#157]
### Explain problem to solve

gloabl permission is only available on hcl format and cluster-api has json format.

### Describe the solution you would like

Options 1:
Use preprocessor with osc-cli ?

### Additional context

None

### Environment

```markdown
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):
- Kernel (e.g. `uname -a`):
- cluster-api-provider-outscale version:
- cluster-api version:
- Install tools:
- Kubernetes Distribution:
- Kubernetes Diestribution version:
```

**Comment by outscale-hmi** [comment]
Image builder global permission exist in both format hcl and json, we'll be available in the next release of Packer
