### ISSUE TITLE
Change default architecture cluster api

### ISSUE THREAD

**Issue by outscale-vbr** [outscale-dev/cluster-api-provider-outscale#161]
### Explain problem to solve

We have a default architecture with cluster api with every parameters which are configurable (vpc, subnet, ....).
The current default CIDR is too limited.

### Describe the solution you would like

We will change this infrastructure to use only 3 subnets (we will merge subnet nat with subnet public) and we will change the default CIDR.

VPC_CIDR: 10.0.0.0/8
WORKER_CIDR: 10.1.0.0/16
MASTER_CIDR: 10.0.1.0/24
PUBLIC_CIDR: 10.0.2.0/24

### Additional context

None

### Environment

```markdown
- Kubernetes version: (use `kubectl version`): v1.22.5-rancher1-1
- OS (e.g. from `/etc/os-release`): CentOS Linux 7 (Core)
- Kernel (e.g. `uname -a`): 3.10.0-1160.15.2.el7.x86_64
- cluster-api-provider-outscale version: v1.1.3
- cluster-api version: current
- Install tools: calico, ingress-nginx, osc-ccm
- Kubernetes Distribution: rke
- Kubernetes Distribution version: v1.3.4
```

**Comment by outscale-hmi** [comment]
Done 
https://github.com/outscale-dev/cluster-api-provider-outscale/pull/206
