### ISSUE TITLE
Study the multi az architecture

### ISSUE THREAD

**Issue by outscale-vbr** [outscale-dev/cluster-api-provider-outscale#162]
### Explain problem to solve

We have already study other provider architecture but have to study the impact of multi az architecture.

### Describe the solution you would like

Find and test the impact of multi az architecture (IAAS, CNI, CSI) and choose at the end an multi az architecture.
It will be implemented in an other release.

### Additional context

None

### Environment

```markdown
- Kubernetes version: (use `kubectl version`): v1.22.5-rancher1-1
- OS (e.g. from `/etc/os-release`): CentOS Linux 7 (Core)
- Kernel (e.g. `uname -a`): 3.10.0-1160.15.2.el7.x86_64
- cluster-api-provider-outscale version: v1.1.3
- cluster-api version: current
- Install tools: calico, ingress-nginx, osc-ccm
- Kubernetes Distribution: rke
- Kubernetes Distribution version: v1.3.4
```

**Comment by outscale-hmi** [comment]
@outscale-mdr studied the multi AZ architecture 
https://wiki.outscale.internal/display/~maxime.dufour/Cluster+Multi-AZ
